- name: "Shipping"
  hosts: shipping
  become: yes
  tasks:
  - name: "Installing maven and mysql"
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql

  - name: "Creating user"
    ansible.builtin.user:
      name: roboshop
      home: /app
      system: true
      shell: /sbin/nologin
      comment: "roboshop system user"

  - name: "Creating directory"
    ansible.builtin.file:
      path: /app
      state: directory

  - name: "Downloading the code"
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
      dest: /tmp/shipping.zip

  - name: "Unzip the files"
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app

  - name: "Maven clean package"
    ansible.builtin.command: mvn clean package

  - name: "Changing the name"
    ansible.builtin.copy:
      src: target/shipping-1.0.jar
      dest: shipping.jar

  - name: "creating service file"
    ansible.builtin.template:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service
      remote_src: yes

  - name: "daemon reload"
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: "Loading schema"
    community.mysql.mysql_db:
      name: "{{ MYSQL_HOST }}"
      state: import
      target: "{{ item }}"
      login_user: root
      login_password: RoboShop@1

  - name: "Start the service"
    ansible.builtin.service:
      name: shipping
      state: restarted
      eanbled: yes

  


  

  

  